### PR TITLE
[RFC]: Rewrite to use Help mode?

### PR DESCRIPTION
**Pull request by kyleam**
Thanks for pydoc.el.  It's great to have Python documentation that feels more like Emacs documentation.  

What do you all think about using Help mode directly (described more in the commit message of 081180d47df2571a7799b78249b250b0040db0a1)?

### CODE REVIEW

**Comment by jkitchin** [comment]
it will be a week or so until I can look at this.

**Comment by jkitchin** [comment]
Wow. This is almost a total rewrite! with some nice new features that seem more robust. Thanks, and sorry it took so long to review this...

**Comment by kyleam** [comment]
Thanks for revisiting this.

I see you've made a merge into master related to this, but something's
seem to gone wrong: it's without the original commit information,
instead consisting of one non-merge commit under your name.

**Comment by jkitchin** [comment]
hm.. that is unfortunate. I had to resolve some merge conflicts at the cmd line, and I wonder if that didn't work right? Any chance you know how to fix that?

**Comment by kyleam** [comment]
> Any chance you know how to fix that?

PR #9 reverts the merge and then re-merges.  The end result code-wise is exactly the same as the current master.

Thanks.

**Comment by jkitchin** [comment]
Thanks for fixing that! I still don't know how the history got lost, but I am glad to see your contributions are logged now.

**Comment by kyleam** [comment]
No problem.  Thanks for merging.

**Pull request merged**
